name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        make lint

    - name: Build
      run: |
        echo GITHUB_REF=$GITHUB_REF GITHUB_SHA=$GITHUB_SHA
        make release

    - name: Create release and upload assets if tag is defined
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/jobs-queue_*.tar.gz
